import { Autoplay, Navigation, Pagination, Thumbs } from "swiper/modules";

export const sliderProps = {
  hero: {
    modules: [Autoplay, Pagination, Navigation],
    loop: true,
    autoplay: { delay: 5000, disableOnInteraction: false },
    pagination: { el: ".dot", clickable: true },
    speed: 800,
  },
  testimonialContentSlider: {
    modules: [Autoplay, Pagination],
    loop: true,
    autoplay: { delay: 4000, disableOnInteraction: false },
    pagination: { el: ".dot", clickable: true },
    speed: 700,
    spaceBetween: 30,
  },
  testimonialImageSlider: {
    modules: [Thumbs],
    loop: true,
    spaceBetween: 10,
    slidesPerView: 3,
    speed: 700,
  },
  testimonialContentSlider2: {
    modules: [Autoplay, Pagination],
    loop: true,
    autoplay: { delay: 4000, disableOnInteraction: false },
    pagination: { el: ".dot-2", clickable: true },
    speed: 700,
  },
  testimonialContentSlider3: {
    modules: [Autoplay, Navigation],
    loop: true,
    autoplay: { delay: 4500, disableOnInteraction: false },
    navigation: { nextEl: ".swiper-button-next", prevEl: ".swiper-button-prev" },
    speed: 700,
  },
  foodSlider: {
    modules: [Autoplay, Navigation],
    loop: true,
    autoplay: { delay: 3000, disableOnInteraction: false },
    slidesPerView: 4,
    spaceBetween: 24,
    speed: 700,
    breakpoints: {
      0: { slidesPerView: 1 },
      576: { slidesPerView: 2 },
      768: { slidesPerView: 3 },
      992: { slidesPerView: 4 },
    },
  },
  brandSlider: {
    modules: [Autoplay],
    loop: true,
    autoplay: { delay: 2000, disableOnInteraction: false },
    slidesPerView: 5,
    spaceBetween: 30,
    speed: 1000,
    breakpoints: {
      0: { slidesPerView: 2 },
      576: { slidesPerView: 3 },
      768: { slidesPerView: 4 },
      992: { slidesPerView: 5 },
    },
  },
  gallerySlider: {
    modules: [Autoplay, Navigation],
    loop: true,
    autoplay: { delay: 3500, disableOnInteraction: false },
    slidesPerView: 3,
    spaceBetween: 24,
    speed: 700,
    breakpoints: {
      0: { slidesPerView: 1 },
      768: { slidesPerView: 2 },
      992: { slidesPerView: 3 },
    },
  },
  instagramSlider: {
    modules: [Autoplay],
    loop: true,
    autoplay: { delay: 2500, disableOnInteraction: false },
    slidesPerView: 5,
    spaceBetween: 0,
    speed: 800,
    breakpoints: {
      0: { slidesPerView: 2 },
      576: { slidesPerView: 3 },
      768: { slidesPerView: 4 },
      992: { slidesPerView: 5 },
    },
  },
  nextSaleSlider: {
    modules: [Autoplay, Navigation],
    loop: true,
    autoplay: { delay: 3000, disableOnInteraction: false },
    slidesPerView: 1,
    speed: 700,
  },
};
